import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { artists } from "./artists";
// ===========================================
// ARTIST EPK (Electronic Press Kit) TABLE
// ===========================================
export const artistEpk = sqliteTable("artist_epk", {
  id: text("id").primaryKey(),
  artistId: text("artist_id").notNull().unique().references(() => artists.id, { onDelete: "cascade" }),
  tagline: text("tagline"),
  genreSpecific: text("genre_specific"),
  subgenres: text("subgenres"),
  artistType: text("artist_type"),
  bioShort: text("bio_short"),
  bioLong: text("bio_long"),
  bioPress: text("bio_press"),
  storyHighlights: text("story_highlights"),
  logoUrl: text("logo_url"),
  logoTransparentUrl: text("logo_transparent_url"),
  logoWhiteUrl: text("logo_white_url"),
  logoBlackUrl: text("logo_black_url"),
  brandColors: text("brand_colors"),
  brandFont: text("brand_font"),
  spotifyMonthlyListeners: integer("spotify_monthly_listeners"),
  spotifyFollowers: integer("spotify_followers"),
  spotifyTopTrack: text("spotify_top_track"),
  appleMusicUrl: text("apple_music_url"),
  youtubeSubscribers: integer("youtube_subscribers"),
  youtubeTotalViews: integer("youtube_total_views"),
  instagramFollowers: integer("instagram_followers"),
  tiktokFollowers: integer("tiktok_followers"),
  totalStreams: integer("total_streams"),
  streamingHighlights: text("streaming_highlights"),
  pressFeatures: text("press_features"),
  blogMentions: text("blog_mentions"),
  interviewUrls: text("interview_urls"),
  editorialPlaylists: text("editorial_playlists"),
  curatedPlaylists: text("curated_playlists"),
  pastShows: text("past_shows"),
  festivalAppearances: text("festival_appearances"),
  notableVenues: text("notable_venues"),
  tourHistory: text("tour_history"),
  collaborations: text("collaborations"),
  producerCredits: text("producer_credits"),
  remixCredits: text("remix_credits"),
  topTracks: text("top_tracks"),
  latestRelease: text("latest_release"),
  upcomingRelease: text("upcoming_release"),
  officialMusicVideos: text("official_music_videos"),
  livePerformanceVideos: text("live_performance_videos"),
  featuredVideo: text("featured_video"),
  visualizerVideos: text("visualizer_videos"),
  behindTheScenes: text("behind_the_scenes"),
  pressQuotes: text("press_quotes"),
  artistEndorsements: text("artist_endorsements"),
  industryTestimonials: text("industry_testimonials"),
  bookingEmail: text("booking_email"),
  bookingPhone: text("booking_phone"),
  managementName: text("management_name"),
  managementEmail: text("management_email"),
  managementPhone: text("management_phone"),
  publicistName: text("publicist_name"),
  publicistEmail: text("publicist_email"),
  labelName: text("label_name"),
  labelContact: text("label_contact"),
  performanceFormat: text("performance_format"),
  setLengthOptions: text("set_length_options"),
  technicalRequirements: text("technical_requirements"),
  backlineNeeds: text("backline_needs"),
  stageRequirements: text("stage_requirements"),
  hospitalityRider: text("hospitality_rider"),
  travelRequirements: text("travel_requirements"),
  pressKitPdfUrl: text("press_kit_pdf_url"),
  hiResPhotosZipUrl: text("hi_res_photos_zip_url"),
  logoPackZipUrl: text("logo_pack_zip_url"),
  technicalRiderPdfUrl: text("technical_rider_pdf_url"),
  stageplotUrl: text("stageplot_url"),
  isPublic: integer("is_public", { mode: "boolean" }).notNull().default(false),
  customSlug: text("custom_slug"),
  theme: text("theme").default("dark"),
  customCss: text("custom_css"),
  showContactForm: integer("show_contact_form", { mode: "boolean" }).notNull().default(true),
  password: text("password"),
  viewCount: integer("view_count").notNull().default(0),
  downloadCount: integer("download_count").notNull().default(0),
  lastViewedAt: integer("last_viewed_at", { mode: "timestamp" }),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});
export const epkPressPhotos = sqliteTable("epk_press_photos", {
  id: text("id").primaryKey(),
  artistId: text("artist_id").notNull().references(() => artists.id, { onDelete: "cascade" }),
  imageUrl: text("image_url").notNull(),
  thumbnailUrl: text("thumbnail_url"),
  hiResUrl: text("hi_res_url"),
  photoType: text("photo_type", { enum: ["portrait", "performance", "styled", "candid", "album_artwork", "promo"] }).notNull().default("portrait"),
  title: text("title"),
  description: text("description"),
  photographer: text("photographer"),
  photographerUrl: text("photographer_url"),
  year: integer("year"),
  width: integer("width"),
  height: integer("height"),
  fileSize: integer("file_size"),
  isFeatured: integer("is_featured", { mode: "boolean" }).notNull().default(false),
  isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});
export const epkTracks = sqliteTable("epk_tracks", {
  id: text("id").primaryKey(),
  artistId: text("artist_id").notNull().references(() => artists.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  releaseDate: integer("release_date", { mode: "timestamp" }),
  coverArtUrl: text("cover_art_url"),
  spotifyUrl: text("spotify_url"),
  spotifyEmbedCode: text("spotify_embed_code"),
  appleMusicUrl: text("apple_music_url"),
  youtubeMusicUrl: text("youtube_music_url"),
  soundcloudUrl: text("soundcloud_url"),
  soundcloudEmbedCode: text("soundcloud_embed_code"),
  streamCount: integer("stream_count"),
  description: text("description"),
  isFeatured: integer("is_featured", { mode: "boolean" }).notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});
export const epkVideos = sqliteTable("epk_videos", {
  id: text("id").primaryKey(),
  artistId: text("artist_id").notNull().references(() => artists.id, { onDelete: "cascade" }),
  title: text("title").notNull(),
  videoType: text("video_type", { enum: ["music_video", "live_performance", "interview", "behind_the_scenes", "visualizer", "lyric_video"] }).notNull().default("music_video"),
  platform: text("platform", { enum: ["youtube", "vimeo", "facebook", "instagram", "tiktok", "other"] }).notNull().default("youtube"),
  videoUrl: text("video_url").notNull(),
  embedCode: text("embed_code"),
  thumbnailUrl: text("thumbnail_url"),
  viewCount: integer("view_count"),
  duration: integer("duration"),
  publishDate: integer("publish_date", { mode: "timestamp" }),
  description: text("description"),
  venue: text("venue"),
  isFeatured: integer("is_featured", { mode: "boolean" }).notNull().default(false),
  isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false),
  sortOrder: integer("sort_order").notNull().default(0),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});
export const epkViews = sqliteTable("epk_views", {
  id: text("id").primaryKey(),
  artistId: text("artist_id").notNull().references(() => artists.id, { onDelete: "cascade" }),
  viewerIp: text("viewer_ip"),
  viewerUserAgent: text("viewer_user_agent"),
  referrer: text("referrer"),
  viewedAt: integer("viewed_at", { mode: "timestamp" }).notNull().default(sql`(unixepoch())`),
});
export type ArtistEpk = typeof artistEpk.$inferSelect;
export type NewArtistEpk = typeof artistEpk.$inferInsert;
export type EpkPressPhoto = typeof epkPressPhotos.$inferSelect;
export type NewEpkPressPhoto = typeof epkPressPhotos.$inferInsert;
export type EpkTrack = typeof epkTracks.$inferSelect;
export type NewEpkTrack = typeof epkTracks.$inferInsert;
export type EpkVideo = typeof epkVideos.$inferSelect;
export type NewEpkVideo = typeof epkVideos.$inferInsert;
export type EpkView = typeof epkViews.$inferSelect;
export const epkSectionLabels = {
  identity: "Identidad & Posicionamiento",
  bios: "Biografías",
  visuals: "Identidad Visual",
  streaming: "Estadísticas de Streaming",
  press: "Prensa & Medios",
  playlists: "Playlists",
  shows: "Shows & Festivales",
  collaborations: "Colaboraciones",
  music: "Música Destacada",
  videos: "Video",
  quotes: "Citas & Testimonios",
  contact: "Contacto",
  technical: "Rider Técnico",
  downloads: "Descargas",
  settings: "Configuración",
};
export const photoTypeLabels = {
  portrait: "Retrato",
  performance: "Performance",
  styled: "Editorial/Estilizado",
  candid: "Candid/Espontáneo",
  album_artwork: "Artwork de Álbum",
  promo: "Promocional",
};
export const videoTypeLabels = {
  music_video: "Video Musical",
  live_performance: "Performance en Vivo",
  interview: "Entrevista",
  behind_the_scenes: "Detrás de Cámaras",
  visualizer: "Visualizer",
  lyric_video: "Lyric Video",
};